s1="let's google"
s2=" the pineapple"
#Concatenation
s3=s1+s2
print(s3)
#Capitalize()
print(s3.capitalize())
#upper()
print(s3.upper())
#lower()
print(s3.lower())
#Count()
print(s3.count('o'))
#isalnum()
print(s3.isalnum())
#isalpha()
print(s3.isalpha())
#isdecimal()
print(s3.isdecimal())
#isdigit()
print(s3.isdigit())
#istitle
print(s3.title())
#islower()
print(s3.islower())
#isupper()
print(s3.isupper())
#isswapcase()
print(s3.swapcase())
#center()
print(s3.center(60))
#endswith()
print(s3.endswith("apple"))
#find()
print(s3.find("pine"))
#replace()
print(s3.replace("pineapple","python"))
#spilt()
print(s3.split())
#strip()
print(s3.lstrip())
str1="My name is {name},i'm {age} year's old & i'm studying {course}"
print(str1.format(name="Anu k Alias",age="24", course="python django"))