# tuple=()
# print(tuple)
# tpl=(1,2,3)
# print(tpl)
# tpl1=(1,"hello",3.4)
# print(tpl1)
# tpl2=("mouse",[8,4,6],(1,2,3))
# print(tpl2)
# tpl3=('luminar technolab')
# print(tpl3.count('a'))
# tpl4=(4,9,3,10,5,45)
# print(sorted(tpl4))
# print(len(tpl2))
# print(tpl3.index('i'))
#indexing
# tpl5=(2,4,8,6,9,34)
# print(tpl5[1])
# print(tpl5[-2])
# #slicing
# print(tpl5[:])
# print(tpl5[1:4])
# print(tpl5[::-2])
#enumerate()
# x=("star","moon","sun")
# y=enumerate(x)
# print(dict(y))
# x=('b','a','n','a','n','a')
# y=enumerate(x)
# print(list(y))

#max(),min(),sum()
tup=(22,3,45,4,256,890,1)
print(max(tup))
print(min(tup))
print(sum(tup))
#Concatenation
# tpli=(1,2,3)
# tplj=(4,5,6)
# print(tpli+tplj)
#repeat
# print(tpli*3)
#all()
# tpl1=(0,)
# tpl2=()
# tpl3=1,
# tpl4=('moon','star',69,[4,5,6,(9,5)],{'name':'Anu','age':24})
# print(all(tpl1))
# print(all(tpl2))
# print(all(tpl3))
# print(all(tpl4))#returns true if tuple is empty or contains true variables

#any()

# tpl1=0,
# tpl2=()
# tpl3=('moon','star',69,[4,5,6,(9,5)],{'name':'Anu','age':24})
# print(any(tpl1))
# print(any(tpl2))
# print(any(tpl3))
